.phony all:
all: 

	gcc -Wall -DPART1 a3.c -o diskinfo
	gcc -Wall -DPART2 a3.c -o disklist
	gcc -Wall -DPART3 a3.c -o diskget
	gcc -Wall -DPART4 a3.c -o diskput

.PHONY clean:
clean:
	-rm diskinfo disklist diskget diskput
